version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: volteras_db
    #restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8181:8000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/usr/src/app
    depends_on:
      - db
    networks:
      - appnet 

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet       

volumes:
  mysql_db_data:

networks:
  appnet:
    driver: bridge